"""Create the example Database

Revision ID: 2284534f10a7
Revises: 733283ff48e3
Create Date: 2022-11-19 17:34:32.515138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2284534f10a7'
down_revision = '733283ff48e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expression', sa.Column('created_at', sa.String(length=255), nullable=False))
    op.add_column('label', sa.Column('created_at', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('label', 'created_at')
    op.drop_column('expression', 'created_at')
    # ### end Alembic commands ###
