"""another

Revision ID: fa9f1427de35
Revises: ee582d59d6b0
Create Date: 2022-11-12 17:54:38.828746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9f1427de35'
down_revision = 'ee582d59d6b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
